### ISSUE TITLE
Specs of C1?

### ISSUE THREAD

**Issue by dersch81** [dokuhn/openDTU-BreakoutBoard#3]
Hi, what are the specs of C1?

**Comment by dokuhn** [comment]
Hi, i used a capacitor with 22uF and 50V voltage resistance, I had many of them at home. But a capacitor with 10uF and 6.3V is a good choice.

**Comment by stefan123t** [comment]
We usually recommend 47-100uF on the Discord but that is just word of mouth. I guess anything between 10 and 100uF should be sound.
@dokuhn thanks for the board!
Are there plans to leave a bit more space for the Elko ?
currently it does not fit easily between the MCU and NRF boards. 
Thanks time and again for your contribution !

If you change the layout it may be good to have the six Test-Pins under the board as removable solder bridges so someone could use a different Pinout between MCU and NRF.
