### ISSUE TITLE
Include female pin headers

### ISSUE THREAD

**Issue by mojoaxel** [dokuhn/openDTU-BreakoutBoard#4]
_First let me thank @dokuhn for creating this board! I've already ordered a handfull and It's amazing._

Now I would like to order some breakout boards where I can simply plug-in the ESP32 and the nRF24L01+ boards without the need to solder. For that fitting straight PCB sockets/pin-headers are missing in the schematics.

![image](https://user-images.githubusercontent.com/600565/206875046-1131f438-1c3f-4942-9e66-303054a743db.png)

Is there a way to add them to the KiCad projekt so that they easily can be manifactured from any PCB- and assembly-service?
Sadly I don't have any experiance with KiCAD, yet and I'm afraid that I make a stupid beginer mistake.

**Comment by dokuhn** [comment]
I thank you for your idea. typically, the schematic is to show the logical connection of electronic components. This is made by the SPI etc. Connection of the two breakout board.  Pin headers etc are part of the physical expression and therefore part of the footprint. At this point one could design a corresponding footrpint with just the pin headers, but it is not really usual.  

Many PCB companies that offer assembly limit the assembly to SMT/SMD. Or do you know a cheap company that solder THT components ? For the future there should be a complete SMD variant.
