### ISSUE TITLE
Publish PCB top and Bottom as *.dxf or *.svg

### ISSUE THREAD

**Issue by HaraldNoack** [dokuhn/openDTU-BreakoutBoard#9]
Hello,
please can you export the kicad-PCB file to top and button svg or dxf (best both) gerber is also an option.

Then everyone can make the pcb.

Thanks for your work!

Best Regards
Harald

**Comment by dokuhn** [comment]
Thank you for your request. The current Gerber files of the last release (with exactly these data the boards are produced) can be found [here](https://github.com/dokuhn/openDTU-BreakoutBoard/releases/tag/1.0.0) In one of my next pushes, I can also put SVG or DXF files there. But I can't give any guarantee for this export. The currently provided data were

a) used by me for the production and
b) by some people from the community. 


Best Regards

Dominik
